// Generates every PNG the game uses from the pixel data in this folder, plus a
// TypeScript index describing where each animation lives in the sheet, so the
// game never hardcodes sprite coordinates.
//
// Run with `npm run art`. Output is committed, so a normal build never runs this.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Grid } from './draw.mjs';
import { blit, encodePng, rowsToRgba } from './png.mjs';
import { PAL } from './palette.mjs';
import { roxyIcon, upscale } from './icon.mjs';
import { CELL, roxyAnimations } from './roxy.mjs';
import * as props from './props.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..');
const PUBLIC_DIR = join(ROOT, 'public');
const GENERATED_DIR = join(ROOT, 'src', 'assets', 'generated');

const ICON_BG = [0x2a, 0x1b, 0x4a, 0xff];

function write(path, width, height, rgba) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, encodePng(width, height, rgba));
  console.log(`  ${path.replace(ROOT, '.')}  ${width}x${height}`);
}

function buildIcons() {
  // 48x48 base: solid background with the 32x32 face inset, which keeps the dog
  // inside the safe zone Android uses when it masks an icon into a circle.
  const base = 48;
  const canvas = new Uint8Array(base * base * 4);
  for (let i = 0; i < base * base; i++) canvas.set(ICON_BG, i * 4);

  const face = rowsToRgba(roxyIcon(), PAL);
  blit(canvas, base, face.rgba, face.width, face.height, 8, 8);

  for (const factor of [4, 12]) {
    const size = base * factor;
    write(join(PUBLIC_DIR, `icon-${size}.png`), size, size, upscale(canvas, base, base, factor));
  }
}

function buildRoxy() {
  const animations = roxyAnimations();
  const names = Object.keys(animations);
  const columns = Math.max(...names.map((n) => animations[n].length));

  const sheet = new Grid(columns * CELL, names.length * CELL);
  const index = {};

  names.forEach((name, row) => {
    animations[name].forEach((frame, column) => {
      frame.blitInto(sheet, column * CELL, row * CELL);
    });
    index[name] = { row, frames: animations[name].length };
  });

  const { width, height, rgba } = rowsToRgba(sheet.rows(), PAL);
  write(join(GENERATED_DIR, 'roxy.png'), width, height, rgba);
  return { index, columns, rows: names.length };
}


/**
 * Pack the props into one sheet with a simple shelf packer and emit the
 * regions, so nothing in the game has to know sprite coordinates by hand.
 */
function buildProps() {
  const items = [
    ['bone', props.bone()],
    ['spring', props.spring(false)],
    ['springUp', props.spring(true)],
    ['spike', props.spike()],
    ['crate', props.crate()],
    ['checkpoint', props.checkpoint(false)],
    ['checkpointLit', props.checkpoint(true)],
    ['goal', props.goal()],
  ];

  // One duck, shared by every world.
  items.push(['walkerA', props.walker(false)]);
  items.push(['walkerB', props.walker(true)]);
  items.push(['flyerA', props.flyer(false)]);
  items.push(['flyerB', props.flyer(true)]);

  const SHEET_WIDTH = 256;
  const PADDING = 1;
  const placed = [];
  let x = 0;
  let y = 0;
  let shelfHeight = 0;

  for (const [name, grid] of items) {
    if (x + grid.width > SHEET_WIDTH) {
      x = 0;
      y += shelfHeight + PADDING;
      shelfHeight = 0;
    }
    placed.push({ name, grid, x, y });
    x += grid.width + PADDING;
    shelfHeight = Math.max(shelfHeight, grid.height);
  }

  const sheet = new Grid(SHEET_WIDTH, y + shelfHeight);
  const index = {};
  for (const item of placed) {
    item.grid.blitInto(sheet, item.x, item.y);
    index[item.name] = { x: item.x, y: item.y, w: item.grid.width, h: item.grid.height };
  }

  const { width, height, rgba } = rowsToRgba(sheet.rows(), PAL);
  write(join(GENERATED_DIR, 'props.png'), width, height, rgba);
  return index;
}

function writeIndex(roxy, propIndex) {
  const lines = [
    '// Generated by tools/gen-art.mjs. Do not edit by hand - run `npm run art`.',
    '',
    `export const CELL = ${CELL};`,
    '',
    'export interface Strip {',
    '  /** Row in the sheet, in cells. */',
    '  readonly row: number;',
    '  readonly frames: number;',
    '}',
    '',
    `export type RoxyAnimation = ${Object.keys(roxy.index)
      .map((n) => `'${n}'`)
      .join(' | ')};`,
    '',
    'export const ROXY: Readonly<Record<RoxyAnimation, Strip>> = {',
    ...Object.entries(roxy.index).map(
      ([name, strip]) => `  ${name}: { row: ${strip.row}, frames: ${strip.frames} },`,
    ),
    '};',
    '',
    'export interface Region {',
    '  readonly x: number;',
    '  readonly y: number;',
    '  readonly w: number;',
    '  readonly h: number;',
    '}',
    '',
    `export type PropName = ${Object.keys(propIndex)
      .map((n) => `'${n}'`)
      .join(' | ')};`,
    '',
    'export const PROPS: Readonly<Record<PropName, Region>> = {',
    ...Object.entries(propIndex).map(
      ([name, r]) => `  ${name}: { x: ${r.x}, y: ${r.y}, w: ${r.w}, h: ${r.h} },`,
    ),
    '};',
    '',
  ];
  const path = join(GENERATED_DIR, 'sprites.ts');
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, lines.join('\n'), 'utf8');
  console.log(`  ${path.replace(ROOT, '.')}`);
}

console.log('Generating art...');
buildIcons();
writeIndex(buildRoxy(), buildProps());
console.log('Done.');
